use ggez::nalgebra::{Point2};

pub const FRAME_WIDTH_PX: f32 = 24.0;
pub const FRAME_HEIGHT_PX: f32 = 24.0;
pub const SPRITESHEET_WIDTH_PX: f32 = 24.0 * 5.0;
pub const SPRITESHEET_HEIGHT_PX: f32 = 24.0 * 2.0;
pub const SCALE: f32 = 2.0;

pub const DRAW_OFFSET_X: f32 = FRAME_WIDTH_PX/2.0*SCALE;
pub const DRAW_OFFSET_Y: f32 = FRAME_HEIGHT_PX/2.0*SCALE;

pub const FRAME_WIDTH_RATIO: f32 = FRAME_WIDTH_PX / SPRITESHEET_WIDTH_PX;
pub const FRAME_HEIGHT_RATIO: f32 = FRAME_HEIGHT_PX / SPRITESHEET_HEIGHT_PX;
